force-app/main/default/objects/TwhatsAppMessage__c/TwhatsAppMessage__c.object-meta.xml
<CustomObject>
    <label>TwhatsApp Message</label>
    <nameField>
        <displayFormat>TWM-{0000000}</displayFormat>
        <label>Message</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TwhatsApp Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TwhatsAppMessage__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TwhatsAppMessage__c/fields/Inbound__c.field-meta.xml
<CustomField>
    <fullName>Inbound__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inbound</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TwhatsAppMessage__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <label>To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TwhatsAppController.cls
public with sharing class TwhatsAppController {
    
    @AuraEnabled
    public static List<TwhatsAppMessage__c> getTwhatsAppMessages() {
        return [SELECT Id, Body__c, To__c, From__c, Inbound__c 
                FROM TwhatsAppMessage__c
                ORDER BY CreatedDate];
    }

    @AuraEnabled
    public static void sendMsg(string msg) {
        TwhatsAppUtility.sendWhatsAppMessage(msg);
    }
}