force-app/main/default/objects/TwhatsAppMessage__c/TwhatsAppMessage__c.object-meta.xml
<CustomObject>
    <label>TwhatsApp Message</label>
    <nameField>
        <displayFormat>TWM-{0000000}</displayFormat>
        <label>Message</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TwhatsApp Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TwhatsAppMessage__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TwhatsAppMessage__c/fields/Inbound__c.field-meta.xml
<CustomField>
    <fullName>Inbound__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inbound</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TwhatsAppMessage__c/fields/To__c.field-meta.xml
<CustomField>
    <fullName>To__c</fullName>
    <label>To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TwhatsAppService.cls
@RestResource(urlMapping='/receive')
global with sharing class TwhatsAppService {
    
    @HttpPost
    global static String doPost() {
        RestRequest req = RestContext.request;
        List<TwhatsAppMessage__c> inserts = new List<TwhatsAppMessage__c>();
        inserts.add(new TwhatsAppMessage__c(
            To__c = req.params.get('To'),
            From__c = req.params.get('From'),
            Body__c = req.params.get('Body'),
            Inbound__c = true
        ));
        insert inserts;
        return 'success';
    }
}